name: Addon Release Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-bot:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup HEMTT
    - run: |
      wget https://github.com/BrettMayson/HEMTT/releases/download/v0.7.6/hemtt
      chmod +x hemtt
      ./hemtt --version
